import True from '../../assets/true.png'
import False from '../../assets/aaa.png'
import s from '../../assets/s.png'
import l from '../../assets/l.png'
import m from '../../assets/m.png'


export const comp = [
    {
      activ: true,
      icon: s,
      footIcon: 'Малый проект',
      title: '400 тыс.руб',
      footTitle: 'примерная стоимость',
      foot: '40 тыс.руб/мес.',
      endFoot: 'последующая поддержка',
      sec11: 'mysql/pgsql',
      sec12: False,
      sec13: True,
      sec14: False,
      sec15: False,
      sec16: False,
      sec21: False,
      sec22: False,
      sec23: False,
      sec31: True,
      sec32: False,
      sec33: 20,
      sec41: False,
      sec42: False,
      sec43: False,
      aaa: false,
      ab: false,
      aa: false,

     
    },
      {
      activ: false,
      icon: m,
      footIcon: 'Средний проект',
      title: '2,1 млн.руб',
      footTitle: 'примерная стоимость',
      foot: '400 тыс.руб/мес.',
      endFoot: 'последующая поддержка',
      sec11: 'mysql/pgsql/clickhouse',
      sec12: True,
      sec13: True,
      sec14: True,
      sec15: False,
      sec16: False,
      sec21: 'Rabbitmq',
      sec22: True,
      sec23: False,
      sec31: False,
      sec32: True,
      sec33: 70,
      sec41: False,
      sec42: False,
      sec43: False,
      aaa: true,
      ab: true,
      aa: false,
    },
  {
      activ: false,
      icon: l,
      footIcon: 'Большой проект',
      title: '7,2 млн.руб',
      footTitle: 'примерная стоимость',
      foot: '1 млн.руб/мес.',
      endFoot: 'последующая поддержка',
      sec11: 'mysql/pgsql/clickhouse',
      sec12: True,
      sec13: True,
      sec14: True,
      sec15: True,
      sec16: True,
      sec21: 'Rabbitmq/ kafka',
      sec22: True,
      sec23: True,
      sec31: False,
      sec32: True,
      sec33: 70,
      sec41: 100,
      sec42: True,
      sec43: True,
      aaa: true,
      ab: true,
      aa: true,
  }
]
// {
//     activ: false,
//     icon: s,
//     footIcon: '',
//     title: '',
//     footTitle: '',
//     foot: '',
//     endFoot: '',
//     sec11: '',
//     sec12: '',
//     sec13: '',
//     sec14: '',
//     sec21: '',
//     sec22: '',
//     sec23: '',
//     sec31: '', 
//     sec32: '', 
//     sec33: '', 
//     sec34: '', 
//     sec41: '',
//     sec42: '',
//     sec43: '',
//     sec44: '',
//     sec45: '',
//     sec46: '',
//     sec47: '',
//     sec48: '',
//     sec49: '',
//     sec410: '',
//     sec411: '',
//   },