import True from "../../../../assets/true.png";
import False from "../../../../assets/aaa.png";
import s from "../../../../assets/s.png";
import l from "../../../../assets/l.png";
import m from "../../../../assets/m.png";

export const comp = [
  {
    activ: true,
    icon: s,
    footIcon: "Малый проект",
    title: "300 тыс.руб",
    footTitle: "примерная стоимость",
    foot: "40 тыс.руб/мес.",
    endFoot: "последующая поддержка",
    sec11: "1",
    sec12: "2",
    sec13: "-",
    sec14: "-",
    sec21: "3 разработчика",
    sec22: "-",
    sec23: "-",
    sec31: True,
    sec32: True,
    sec33: False,
    sec34: False,
    sec35: False,
    sec41: True,
    sec42: True,
    sec43: True,
    sec44: True,
    sec45: False,
    sec46: "-",
    sec47: False,
    sec48: False,
    sec49: False,
    sec410: False,
    sec411: False,
  },
  {
    activ: false,
    icon: m,
    footIcon: "Средний проект",
    title: "800 тыс.руб",
    footTitle: "примерная стоимость",
    foot: "200 тыс.руб/мес.",
    endFoot: "последующая поддержка",
    sec11: "5",
    sec12: "5",
    sec13: "-",
    sec14: "-",
    sec21: "2 команды",
    sec22: "-",
    sec23: "-",
    sec31: True,
    sec32: True,
    sec33: True,
    sec34: False,
    sec35: False,
    sec41: False,
    sec42: False,
    sec43: True,
    sec44: True,
    sec45: True,
    sec46: "2",
    sec47: True,
    sec48: False,
    sec49: False,
    sec410: False,
    sec411: False,
  },
  {
    activ: false,
    icon: l,
    footIcon: "Большой проект",
    title: "2,5 млн.руб",
    footTitle: "примерная стоимость",
    foot: "900 тыс.руб/мес.",
    endFoot: "последующая поддержка",
    sec11: "3",
    sec12: "15",
    sec13: "5",
    sec14: "2",
    sec21: "5 команд",
    sec22: "2",
    sec23: "1",
    sec31: True,
    sec32: True,
    sec33: True,
    sec34: False,
    sec35: False,
    sec41: False,
    sec42: False,
    sec43: True,
    sec44: True,
    sec45: True,
    sec46: "3",
    sec47: True,
    sec48: True,
    sec49: True,
    sec410: True,
    sec411: True,
  },
];
// {
//     activ: false,
//     icon: s,
//     footIcon: '',
//     title: '',
//     footTitle: '',
//     foot: '',
//     endFoot: '',
//     sec11: '',
//     sec12: '',
//     sec13: '',
//     sec14: '',
//     sec21: '',
//     sec22: '',
//     sec23: '',
//     sec31: '',
//     sec32: '',
//     sec33: '',
//     sec34: '',
//     sec41: '',
//     sec42: '',
//     sec43: '',
//     sec44: '',
//     sec45: '',
//     sec46: '',
//     sec47: '',
//     sec48: '',
//     sec49: '',
//     sec410: '',
//     sec411: '',
//   },
